package com.neuedu.business_interface.dao;


import com.neuedu.business_interface.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);

    Cart SelectCartByUserIdAndProductId(@Param("userId") Integer userId,@Param("productId") Integer productId);

    /**
     * 查询用户购物车信息
     * @param userId
     * @return
     */
    List<Cart> selectCartByUserId(Integer userId);
    /**
     *统计用户购物信息是否全选
     */
    int isCheckedAll(Integer userId);

    /**
     * 删除购物车的某些商品
     */
    int deleteByUseridAndProductIds(@Param("userId") Integer userId,
                                    @Param("productIdList") List<Integer> productIdList);

    /**
     * 操作购物车是否选中
     *
     */
    int selectOrUnselectProduct(@Param("userId") Integer userId,
                                @Param("productId") Integer productId,
                                @Param("check") Integer check);
    /**
     * 查询购物车中产品数量
     */
    int get_cart_product_count(Integer userId);
    /**
     * 查询用户已选中商品
     */
    List<Cart> findCartListByUserIdAndChecked(Integer userId);

    /**
     * 批量删除
     */
    int batchDelete(List<Cart> cartList);

}
