package com.neuedu.business_interface.dao;


import com.neuedu.business_interface.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 判断用户名是否存在
     * @return  1:存在  0：不存在
     **/
    int exitsUsername(@Param("username") String username);

    /**
     * 判断邮箱是否存在
     * @return  1:存在  0：不存在
     **/
    int exitsEmail(@Param("email") String email);

    UserInfo findByUsernameAndPassword(@Param("username") String username,@Param("password")String password);

    /**
     * 查找密保问题
     */
    String selectQuestionByUsername(String username);


    int selectByUsernameAndQuestionAndAnswer(@Param("username") String username,@Param("question") String question,@Param("answer") String answer);

    /**
     * 修改用户密码
     */
    int updateUserPassword(@Param("username") String username,@Param("password") String passwordNew);

}